/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.javaConnection;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Abdelrhman Salah
 */
public class add_prescription extends javax.swing.JFrame {

    /**
     * Creates new form add_prescription
     */
    public add_prescription() {
        initComponents();
        s = new TreeSet<String>();

        date_chooser.setDate(new Date());

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        get_data();
    }

    private void get_data() {
        try {
            String sql = "select patient_name from data";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                s.add(rs.getString(1));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private static BufferedImage resize(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    private void clean() {
        quantity_txt.setText("");
        entered_name_txt.setText("");
        patient_name_txt.setText("");
        job_txt.setText("");
        degree_combo.setSelectedIndex(0);
        image_label.setIcon(null);
        person_image = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        quantity_txt = new javax.swing.JTextField();
        entered_name_txt = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image_label = new javax.swing.JLabel();
        attachimage_btn = new javax.swing.JButton();
        patient_name_txt = new javax.swing.JTextField();
        job_txt = new javax.swing.JTextField();
        degree_combo = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel1.setText("تسجيل روشتة");

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel2.setText("التاريخ");

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel4.setText("المبلغ");

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel5.setText("الأسم");

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel6.setText("القائم بالصرف");

        jLabel8.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel8.setText("الرتبة");

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel9.setText("الوظيفة");

        add_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Ok_25px.png"))); // NOI18N
        add_btn.setText("تسجيل");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        quantity_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        entered_name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entered_name_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setDoubleBuffered(true);
        jDesktopPane1.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        image_label.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        image_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_label.setAutoscrolls(true);
        image_label.setIconTextGap(0);
        jDesktopPane1.setLayer(image_label, javax.swing.JLayeredPane.POPUP_LAYER);
        jDesktopPane1.add(image_label);
        image_label.setBounds(0, 0, 460, 490);

        attachimage_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attachimage_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add_25px.png"))); // NOI18N
        attachimage_btn.setText("تحميل صورة");
        attachimage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachimage_btnActionPerformed(evt);
            }
        });

        patient_name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patient_name_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        patient_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patient_name_txtKeyReleased(evt);
            }
        });

        job_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        job_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        degree_combo.setFont(new java.awt.Font("Arabic Typesetting", 0, 50)); // NOI18N
        degree_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "لواء", "عميد", "عقيد", "مقدم", "رائد", "نقيب", "ملازم أول", "ملازم" }));

        back_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_35px.png"))); // NOI18N
        back_btn.setText("رجوع");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 0, 40)); // NOI18N
        jLabel3.setText("ج.م");

        date_chooser.setDateFormatString("dd/MM/yyyy");
        date_chooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entered_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(305, 305, 305))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(degree_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(patient_name_txt)
                                            .addComponent(job_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(95, 95, 95)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(attachimage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(302, 302, 302))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(back_btn)
                .addGap(353, 353, 353)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(entered_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(jLabel2))
                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attachimage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patient_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(degree_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(job_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1119, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attachimage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachimage_btnActionPerformed

        try {
            JFileChooser chooser = new JFileChooser();
            int result = chooser.showOpenDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {

                String filename = chooser.getSelectedFile().getAbsolutePath();

                File input = new File(filename);
                BufferedImage image = ImageIO.read(input);

                BufferedImage resized = resize(image, 500, 400);

                File output = new File("src\\images\\" + input.getName());
                ImageIO.write(resized, "jpeg", output);

                FileInputStream fis = new FileInputStream(output);

                ByteArrayOutputStream baos = new ByteArrayOutputStream();

                byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    baos.write(buf, 0, readNum);
                }

                person_image = baos.toByteArray();
                ImageIcon formate = new ImageIcon(person_image);
                image_label.setIcon(formate);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_attachimage_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        try {
            if (person_image != null && !quantity_txt.getText().equals("") && !entered_name_txt.getText().equals("") && !patient_name_txt.getText().equals("") && !job_txt.getText().equals("")) {

                String sql = "insert into data (date,quantity,entered_name,image,patient_name,degree,job) values(?,?,?,?,?,?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1, myFormat.format(date_chooser.getDate()));
                pst.setString(2, quantity_txt.getText());
                pst.setString(3, entered_name_txt.getText());
                pst.setBytes(4, person_image);
                pst.setString(5, patient_name_txt.getText());
                pst.setString(6, degree_combo.getSelectedItem().toString());
                pst.setString(7, job_txt.getText());
                pst.execute();
                clean();
                JOptionPane.showMessageDialog(null, "تم التسجيل بنجاح");
            } else {
                JOptionPane.showMessageDialog(null, "من فضلك املأ جميع البيانات!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.dispose();
        main m = new main();
        m.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void patient_name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patient_name_txtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE || patient_name_txt.getText().equals("")) {
        } else {
            String to_check = patient_name_txt.getText();
            int to_check_len = to_check.length();
            for (String data : s) {

                String check_from_data = "";
                for (int i = 0; i < to_check_len; i++) {
                    if (to_check_len <= data.length()) {
                        check_from_data = check_from_data + data.charAt(i);
                    }
                }

                if (check_from_data.equals(patient_name_txt.getText())) {

                    patient_name_txt.setText(data);
                    patient_name_txt.setSelectionStart(to_check_len);
                    patient_name_txt.setSelectionEnd(data.length());

                }

            }
        }
    }//GEN-LAST:event_patient_name_txtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_prescription().setVisible(true);
            }
        });
    }
    Connection con = javaConnection.ConnecrDB();
    PreparedStatement pst = null;
    ResultSet rs = null;
    SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
    byte[] person_image = null;
    Set<String> s;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton attachimage_btn;
    private javax.swing.JButton back_btn;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JComboBox<String> degree_combo;
    private javax.swing.JTextField entered_name_txt;
    private javax.swing.JLabel image_label;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField job_txt;
    private javax.swing.JTextField patient_name_txt;
    private javax.swing.JTextField quantity_txt;
    // End of variables declaration//GEN-END:variables
}
