/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.javaConnection;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdelrhman Salah
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        get_data();

    }

    private void clean() {
        edit_quantity_txt.setText("");
        edit_entered_name_txt.setText("");
        edit_patient_name_txt.setText("");
        edit_job_txt.setText("");
        edit_degree_combo.setSelectedIndex(0);
        edit_image_label.setIcon(null);
        person_image = null;
    }

    private static BufferedImage resize(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    private void get_data() {
        try {
            Object row_data[] = new Object[7];
            DefaultTableModel model = (DefaultTableModel) data_table.getModel();
            for (int i = data_table.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            String sql = "select * from data";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                row_data[0] = rs.getString("entered_name");
                row_data[1] = rs.getString("quantity");
                row_data[2] = rs.getString("date");
                row_data[3] = rs.getString("job");
                row_data[4] = rs.getString("patient_name");
                row_data[5] = rs.getString("degree");
                row_data[6] = rs.getString("id");
                model.addRow(row_data);
            }
            sql = "select patient_name from data";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                s.add(rs.getString(1));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void search() {
        try {
            Object row_data[] = new Object[7];
            DefaultTableModel model = (DefaultTableModel) data_table.getModel();
            for (int i = data_table.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            String sql = "select * from data where patient_name like '" + search_txt.getText() + "%'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                row_data[0] = rs.getString("entered_name");
                row_data[1] = rs.getString("quantity");
                row_data[2] = rs.getString("date");
                row_data[3] = rs.getString("job");
                row_data[4] = rs.getString("patient_name");
                row_data[5] = rs.getString("degree");
                row_data[6] = rs.getString("id");
                model.addRow(row_data);
            }
            sql = "select patient_name from data";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                s.add(rs.getString(1));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        edit_quantity_txt = new javax.swing.JTextField();
        edit_entered_name_txt = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        edit_image_label = new javax.swing.JLabel();
        edit_attachimage_btn = new javax.swing.JButton();
        edit_patient_name_txt = new javax.swing.JTextField();
        edit_job_txt = new javax.swing.JTextField();
        edit_degree_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        edit_date_chooser = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        delete_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();

        data_dialog.setTitle("بيانات الروشتة");
        data_dialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("بيانات الروشتة");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("التاريخ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("المبلغ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("الأسم");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("القائم بالصرف");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("الرتبة");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("الوظيفة");

        update_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Repeat_35px.png"))); // NOI18N
        update_btn.setText("تحديث");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        edit_quantity_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edit_entered_name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_entered_name_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setDoubleBuffered(true);
        jDesktopPane1.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        edit_image_label.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        edit_image_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_image_label.setAutoscrolls(true);
        edit_image_label.setIconTextGap(0);
        jDesktopPane1.setLayer(edit_image_label, javax.swing.JLayeredPane.POPUP_LAYER);
        jDesktopPane1.add(edit_image_label);
        edit_image_label.setBounds(0, 0, 450, 470);

        edit_attachimage_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_attachimage_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Synchronize_25px.png"))); // NOI18N
        edit_attachimage_btn.setText("تعديل الصورة");
        edit_attachimage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_attachimage_btnActionPerformed(evt);
            }
        });

        edit_patient_name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_patient_name_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edit_patient_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edit_patient_name_txtKeyReleased(evt);
            }
        });

        edit_job_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_job_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        edit_degree_combo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edit_degree_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "لواء", "عميد", "عقيد", "مقدم", "رائد", "نقيب", "ملازم أول", "ملازم" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("ج.م");

        edit_date_chooser.setDateFormatString("dd/MM/yyyy");
        edit_date_chooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete_35px.png"))); // NOI18N
        delete_btn.setText("حذف");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit_entered_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(edit_quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(edit_date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(edit_attachimage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edit_patient_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edit_degree_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(update_btn))
                                    .addComponent(edit_job_txt))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3)))
                .addGap(58, 58, 58))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(edit_quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(edit_entered_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2)
                    .addComponent(edit_date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edit_patient_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edit_degree_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(edit_job_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit_attachimage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4)))
        );

        javax.swing.GroupLayout data_dialogLayout = new javax.swing.GroupLayout(data_dialog.getContentPane());
        data_dialog.getContentPane().setLayout(data_dialogLayout);
        data_dialogLayout.setHorizontalGroup(
            data_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        data_dialogLayout.setVerticalGroup(
            data_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_dialogLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("بحث");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        data_table.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "القائم بالصرف", "المبلغ", "التاريخ", "الوظيفة", "الأسم", "الدرجة", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data_table.setRowHeight(30);
        data_table.setRowMargin(2);
        data_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_table);
        if (data_table.getColumnModel().getColumnCount() > 0) {
            data_table.getColumnModel().getColumn(0).setMaxWidth(250);
            data_table.getColumnModel().getColumn(1).setMaxWidth(150);
            data_table.getColumnModel().getColumn(2).setMaxWidth(200);
            data_table.getColumnModel().getColumn(3).setMaxWidth(400);
            data_table.getColumnModel().getColumn(4).setMaxWidth(400);
            data_table.getColumnModel().getColumn(5).setMaxWidth(100);
            data_table.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        back_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout Rounded Left_35px.png"))); // NOI18N
        back_btn.setText("رجوع");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بحث", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        search_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back_btn)
                .addGap(506, 506, 506)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1248, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.dispose();
        main m = new main();
        m.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try {
            if (!edit_quantity_txt.getText().equals("") && !edit_entered_name_txt.getText().equals("") && !edit_patient_name_txt.getText().equals("") && !edit_job_txt.getText().equals("")) {

                String sql = "update data set date=?,quantity=?,entered_name=?,image=?,patient_name=?,degree=?,job=? where id='" + id + "'";
                pst = con.prepareStatement(sql);
                pst.setString(1, myFormat.format(edit_date_chooser.getDate()));
                pst.setString(2, edit_quantity_txt.getText());
                pst.setString(3, edit_entered_name_txt.getText());
                pst.setBytes(4, person_image);
                pst.setString(5, edit_patient_name_txt.getText());
                pst.setString(6, edit_degree_combo.getSelectedItem().toString());
                pst.setString(7, edit_job_txt.getText());
                pst.execute();
                get_data();
                JOptionPane.showMessageDialog(null, "تم التحديث بنجاح");
            } else {
                JOptionPane.showMessageDialog(null, "من فضلك املأ جميع البيانات!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void edit_attachimage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_attachimage_btnActionPerformed

        try {
            JFileChooser chooser = new JFileChooser();
            int result = chooser.showOpenDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {

                String filename = chooser.getSelectedFile().getAbsolutePath();

                File input = new File(filename);
                BufferedImage image = ImageIO.read(input);

                BufferedImage resized = resize(image, 500, 400);

                File output = new File("src\\images\\" + input.getName());
                ImageIO.write(resized, "jpeg", output);

                FileInputStream fis = new FileInputStream(output);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();

                byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    baos.write(buf, 0, readNum);
                }

                person_image = baos.toByteArray();
                ImageIcon formate = new ImageIcon(person_image);
                edit_image_label.setIcon(formate);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_edit_attachimage_btnActionPerformed

    private void edit_patient_name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_patient_name_txtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE || edit_patient_name_txt.getText().equals("")) {
        } else {
            String to_check = edit_patient_name_txt.getText();
            int to_check_len = to_check.length();
            for (String data : s) {

                String check_from_data = "";
                for (int i = 0; i < to_check_len; i++) {
                    if (to_check_len <= data.length()) {
                        check_from_data = check_from_data + data.charAt(i);
                    }
                }

                if (check_from_data.equals(edit_patient_name_txt.getText())) {

                    edit_patient_name_txt.setText(data);
                    edit_patient_name_txt.setSelectionStart(to_check_len);
                    edit_patient_name_txt.setSelectionEnd(data.length());

                }

            }
        }
    }//GEN-LAST:event_edit_patient_name_txtKeyReleased

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "هل تريد حذف هذا السجل ؟!", "حذف ", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "delete from data where id='" + id + "'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح");
                clean();
                get_data();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void data_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_tableMouseClicked

        try {
            edit_date_chooser.setDate(myFormat.parse(data_table.getModel().getValueAt(data_table.getSelectedRow(), 2).toString()));
            edit_quantity_txt.setText(data_table.getModel().getValueAt(data_table.getSelectedRow(), 1).toString());
            edit_entered_name_txt.setText(data_table.getModel().getValueAt(data_table.getSelectedRow(), 0).toString());
            edit_patient_name_txt.setText(data_table.getModel().getValueAt(data_table.getSelectedRow(), 4).toString());
            edit_job_txt.setText(data_table.getModel().getValueAt(data_table.getSelectedRow(), 3).toString());
            edit_degree_combo.setSelectedItem(data_table.getModel().getValueAt(data_table.getSelectedRow(), 5).toString());
            id = data_table.getModel().getValueAt(data_table.getSelectedRow(), 6).toString();
            String sql = "select image from data where id='" + id + "'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.first()) {
                person_image = rs.getBytes("image");
                formate = new ImageIcon(person_image);
                edit_image_label.setIcon(formate);
            }
            data_dialog.setSize(1070, 775);
            data_dialog.setLocationRelativeTo(null);
            data_dialog.setVisible(true);
            data_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    data_dialog.dispose();
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_data_tableMouseClicked

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        search();
    }//GEN-LAST:event_search_txtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }
    Connection con = javaConnection.ConnecrDB();
    PreparedStatement pst = null;
    ResultSet rs = null;
    SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
    byte[] person_image = null;
    ImageIcon formate = null;
    Set<String> s = new TreeSet<String>();
    String id = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JDialog data_dialog;
    private javax.swing.JTable data_table;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_attachimage_btn;
    private com.toedter.calendar.JDateChooser edit_date_chooser;
    private javax.swing.JComboBox<String> edit_degree_combo;
    private javax.swing.JTextField edit_entered_name_txt;
    private javax.swing.JLabel edit_image_label;
    private javax.swing.JTextField edit_job_txt;
    private javax.swing.JTextField edit_patient_name_txt;
    private javax.swing.JTextField edit_quantity_txt;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables

}
